name: CI
on: [push, pull_request]
jobs:
  allure-report:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install npm dependencies, cache them correctly
      - name: Install dependencies
        uses: cypress-io/github-action@v5
        with:
          runTests: false
      - name: Run Cypress tests
        continue-on-error: true
        run: npm run cypress:run
      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 30

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{secrets.ALLURE_REPORT}}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "Allure report deployed: https://nikitashmatko112112.github.io/leadtesthack"
