name: e2e-tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout
        uses: actions/checkout@v3

      # Шаг 2: Установка зависимостей
      - name: Install dependencies
        run: npm install

      # Шаг 3: Запуск тестов с помощью Cypress
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm run cypress:run
          browser: chrome
          headed: false
          record: false

  allure-report:
    needs: cypress-run
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Установка Allure CLI
      - name: Install Allure CLI
        run: |
          sudo apt-add-repository ppa:qameta/allure -y
          sudo apt-get update -y
          sudo apt-get install allure -y

      # Шаг 2: Генерация отчета Allure
      - name: Generate Allure report
        run: |
          npm run allure:report

      # Шаг 3: Публикация отчета на GitHub Pages
      - name: Publish Allure report to GitHub Pages
        uses: peaceiris/actions-allure@v2
        with:
          version: "2.13.8"
          report_dir: ./allure-report
          github_token: ${{secrets.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}}
          publish_dir: ./docs
